version: '3.8'

services:
  server:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      NODE_ENV: production
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mainAdmin1
      MYSQL_DATABASE: files_popovych
      MYSQL_USER: proger
      MYSQL_PASSWORD: mainAdmin1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
