name: Check linting and formating
on: push
jobs:
  eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependency
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Check prettier
        run: npm run prettier-check
